### ISSUE TITLE
Adjectives not correctly dereferenced to sense keys

### ISSUE THREAD

**Issue by mrmechko** [mrmechko/SWordNet#5]
```scala
key not found: a00225912
java.util.NoSuchElementException: key not found: a00225912
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.mechko.swordnet.SRelationPointer.getTarget(SRelationType.scala:77)
	at org.mechko.swordnet.SWordNet$$anonfun$relations$1.apply(SWordNet.scala:57)
	at org.mechko.swordnet.SWordNet$$anonfun$relations$1.apply(SWordNet.scala:57)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at org.mechko.swordnet.SWordNet$.relations(SWordNet.scala:57)
	at org.mechko.swordnet.SKey.getRelation(SKey.scala:25)
```

**Comment by mrmechko** [comment]
It seems what was happening was that the pos for the synset offset was being determined by the data-file the offset came from.  That was fine for everything except for satellites.  Satellites are encoded in the `sstype` field of the wordnet files. Using that instead seems to work.

Testing a little before I close the issue

**Comment by mrmechko** [comment]
On closer inspection, it was an inconsistency in the code for storing relationships.  The `_offset2synset` map already used this fact.  Closing.

**Comment by mrmechko** [comment]
Mistook the outgoing link for the incoming link. Sad face.

**Comment by mrmechko** [comment]
Ok, the bigger issue was that I forgot that the semantic pointers in the `source/target` field are annoying: `0000` represents a semantic link between synsets while `0102` represents a lexical link.  This means that `01` points to the first element of the list, which is at index 0.  It would have been nice if they used an extra byte, but oh well.
